config/routes.rb
Rails.application.routes.draw do
  root to:'top_page#index'
  get 'home/index'

  resources :users, only: [:new, :create]
  resources :user_sessions, only: [:new, :create, :destroy]
  resource :profile, only: %i[show edit update]
  resources :spots do
    resources :feedbacks, only: %i[create destroy edit update], shallow: true
    resources :likes, only: [:create, :destroy]
  end
  get '/sign_up', to: 'users#new'
  get '/sign_in', to: 'user_sessions#new'
  delete '/sign_out', to: 'user_sessions#destroy', as: :sign_out
  get "guest_login", to: "users#guest_login"
  post "oauth/callback", to: "oauths#callback"
  get "oauth/callback", to: "oauths#callback"
  get "oauth/:provider", to: "oauths#oauth", as: :auth_at_provider
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/spot.rb
class Spot < ApplicationRecord
  belongs_to :user
  has_many :spot_images, dependent: :destroy
  has_many :feedbacks, dependent: :destroy
  has_many :spots_tags, dependent: :destroy
  has_many :tags, through: :spots_tags
  accepts_nested_attributes_for :spot_images, allow_destroy: true
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  geocoded_by :address
  after_validation :geocode

  validates :spot_name, presence: true
  validates :address, presence: true

  def self.ransackable_attributes(auth_object = nil)
    ["address", "comment", "created_at", "id", "latitude", "longitude", "spot_name", "updated_at", "user_id"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["feedbacks", "spot_images", "spots_tags", "tags", "user"]
  end

  def like_user(user_id)
    likes.find_by(user_id: user_id)
  end
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController

  before_action :require_login, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_spot, only: [:edit, :update, :destroy]

  def index
    @q = Spot.ransack(params[:q])
    @spots = @q.result.includes(:user, :tags, :feedbacks, :likes).order(created_at: :desc).page(params[:page]).per(5)

    if @spots.empty?
      flash[:alert] = I18n.t('errors.messages.no_results_found')
      redirect_to spots_path
    end
  end

  def new
    @spot = Spot.new
    @spot.spot_images.build
  end

  def create
    @spot = current_user.spots.new(spot_params)
  
    if params[:spot][:tag_ids].present? && !Tag.where(id: params[:spot][:tag_ids]).count == params[:spot][:tag_ids].count
      flash[:error] = t('posts.create.fall')
      render :new and return
    end
  
    if @spot.save
      redirect_to spots_path, notice: t('posts.create.success')
    else
      flash[:error] = t('posts.create.fall')
      render :new
    end
  end

  def show
    @spot = Spot.find(params[:id])
    @feedback = Feedback.new
    @feedbacks = @spot.feedbacks.includes(:user).order(created_at: :desc)
    @like = @spot.like_user(current_user.id) if current_user
  end

  def edit;end
  
  def update
    if @spot.update(spot_params)
      redirect_to @spot, notice: t('posts.update.success')
    else
      render :edit
    end
  end

  def destroy
    @spot.destroy
    redirect_to spots_path, notice: t('posts.destroy.success')
  end

  private 

  def spot_params
    # `tag_ids`が存在しない場合は、デフォルトで空の配列を設定
    params.require(:spot).permit(:spot_name, :address, :latitude, :longitude, :comment, spot_images_attributes: [:id, :image, :_destroy]).tap do |whitelisted|
      whitelisted[:tag_ids] = params[:spot][:tag_ids] || []
    end
  end

  def require_login
    unless logged_in?
      flash[:error] = t('posts.new.fall')
      redirect_to new_user_session_path # ログインページへのパスを指定
    end
  end

  def set_spot
    @spot = current_user.spots.find_by(id: params[:id])
  end
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/views/spots/_crud_menus.html.erb
<ul class='crud-menu-btn list-inline float-right'>
  <li class="list-inline-item">
    <%= link_to edit_spot_path(spot), id: "button-edit-#{spot.id}" do %>
      <svg class="h-7 w-7 text-purple-500"  width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">  <path stroke="none" d="M0 0h24v24H0z"/>  <path d="M4 20h4l10.5 -10.5a1.5 1.5 0 0 0 -4 -4l-10.5 10.5v4" />  <line x1="13.5" y1="6.5" x2="17.5" y2="10.5" /></svg>
    <% end %>
  </li>
  <li class="list-inline-item">
    <%= link_to spot_path(spot), id: "button-delete-#{spot.id}", method: :delete, data: {confirm: t('defaults.message.delete_confirm')} do %>
      <svg class="h-7 w-7 text-purple-500"  width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">  <path stroke="none" d="M0 0h24v24H0z"/>  <line x1="4" y1="7" x2="20" y2="7" />  <line x1="10" y1="11" x2="10" y2="17" />  <line x1="14" y1="11" x2="14" y2="17" />  <path d="M5 7l1 12a2 2 0 0 0 2 2h8a2 2 0 0 0 2 -2l1 -12" />  <path d="M9 7v-3a1 1 0 0 1 1 -1h4a1 1 0 0 1 1 1v3" /></svg>
    <% end %>
  </li>
</ul>

app/views/spots/_form.html.erb
<div class="h-full pt-10 pb-10">
  <div class="my-4 flex flex-col 2xl:flex-row space-y-4 2xl:space-y-0 2xl:space-x-4">
    <div class="w-full flex flex-col 2xl:w-1/3">
      <div class="flex-1 bg-white rounded-lg shadow-xl p-8 flex flex-col justify-center">
        <h4 class="text-xl text-gray-900 font-bold mb-5"><%= t('posts.new.title') %></h4>
          <%= form_with model: @spot, local: true do |f| %>
            <ul class="mt-2 text-gray-700">
              <li class="flex border-y py-2 pt-5 pb-5">
                <%= f.label :spot_name , class: "font-bold w-24 text-sm" %>
                <%= f.text_field :spot_name ,class: "text-gray-700" %>
              </li>
              <li class="flex border-b py-2 pt-5 pb-5">
                <%= f.label :address, class: "font-bold w-24 text-sm" %>
                <%= f.text_field :address, class: "text-gray-700" %>
              </li>
              <li class="flex flex-col border-b py-2 pt-5 pb-5">
                <%= f.label :detail_info, t('posts.new.detail_info'), class: "font-bold text-sm mb-2" %>
                <% Tag.all.each do |tag| %> 
                  <div class="flex items-center mt-1">
                    <%= f.check_box :tag_ids, { multiple: true, id: "tag_#{tag.id}" }, tag.id, nil %> 
                    <%= f.label "tag_#{tag.id}", tag.content.humanize, class: "ml-2 text-sm" %> 
                  </div>
                <% end %>
              </li>
              <li class="flex flex-col border-b py-2 pt-5 pb-5">
                <%= f.fields_for :spot_images do |spot_image_form| %>
                  <div class="form-group mt-2">
                    <%= spot_image_form.label :image, class: "text-gray-900 font-bold " %>
                    <%= spot_image_form.file_field :image, multiple: true, name: "spot[spot_images_attributes][][image]", class: "form-control", accept: 'image/*', onchange: 'previewImage(this)' %>
                  </div>
                <% end %>
                <div id="preview-container" class="flex flex-wrap -mx-1"></div>
              </li>
              <li class="flex border-b py-2 pt-5 pb-5">
                <%= f.label :comment, class: "text-gray-900 font-bold mr-2 text-sm" %>
                <%= f.text_field :comment, class: "mt-2 text-gray-700 pt-8 pb-8 pl-12" %>
              </li>
            </ul>
            <div class="flex justify-center mt-10">
              <%= f.submit t('posts.new.post'), class: "bg-purple-500 text-white font-bold py-2 px-4 rounded hover:bg-purple-700 transition duration-150 ease-in-out" %>
            </div>
          <%end%>
      </div>
    </div>
  </div>
</div>

<script>
  function previewImage(input) {
    const previewContainer = document.getElementById('preview-container');
    previewContainer.innerHTML = ''; // コンテナを空にする

    if (input.files) {
      const files = Array.from(input.files);

      files.forEach(file => {
        const reader = new FileReader();

        reader.onload = function(e) {
          const img = document.createElement('img');
          img.src = e.target.result;
          img.style.width = '50px'; // サイズを100x100に設定
          img.style.height = '50px';
          img.classList.add('object-cover', 'm-1'); // オブジェクトフィットとマージンを調整
          previewContainer.appendChild(img);
        };

        reader.readAsDataURL(file);
      });
    }
  }
</script>

app/views/spots/_spot.html.erb
<section class="py-1 ">
  <div class="w-full lg:w-8/12 px-4 mx-auto mt-6">
    <div class="relative flex flex-col min-w-0 break-words w-full mb-6 shadow-lg rounded-lg bg-blueGray-100 border-0 h-full">
      <%= link_to spot_path(spot), class: "block" do %>  
        <div class="flex flex-col items-center justify-center h-full bg-green-50">
          <div id="spot-id-<%= spot.id %>">
            <div class="card-body p-5">
              <ul class="list-inline">
                <!-- スポットタイトル -->
                <li class="list-inline-item-spot_title">
                  <div class="flex items-center space-x-1">
                    <h4 class="card-title">
                      <%= t('activerecord.attributes.spot.spot_name') %>:
                      <%= spot.spot_name %>
                    </h4>
                </li>
                <li class="list-inline-item-spot_title">
                  <div class="flex items-center space-x-1">
                    <h4 class="card-address">
                      <%= t('activerecord.attributes.spot.address') %>:
                      <%= spot.address %>
                    </h4>
                  </div>
                </li>
                <!-- タグ -->
                <li class="list-inline-item-spot_title">
                  <div class="flex flex-wrap items-center">
                    <% if spot.tags.any? %>
                      <% spot.tags.each do |tag| %>
                        <div class="flex items-center mt-1">
                          <span class="bg-purple-500 text-white text-sm font-semibold mr-2 px-4 py-1 rounded-full dark:bg-purple-600 dark:text-white">
                            <%= tag.content.humanize %>
                          </span>
                        </div>
                      <% end %>
                    <% end %>
                  </div>
                </li>
                <!-- ユーザー情報 -->
                <li class="list-inline-item-user">
                  <div class="flex flex-row items-center space-x-2">
                    <% if spot.user.avater.present? %> 
                      <%= image_tag spot.user.avater_url, class:"w-8 border-4 border-white rounded-full" %>
                    <% else %>
                      <%= image_tag("default.png", class:"w-8 border-4 border-white rounded-full") %>
                    <% end %>
                    <span><%= spot.user.first_name %> <%= spot.user.last_name %></span>
                  </div>
                </li>

                <!-- コメント -->
                <li class="list-inline-item-comment">
                  <%= t('activerecord.attributes.spot.comment') %>:
                  <%= spot.comment %>
                </li>
                
                <!-- 投稿時間 -->
                <li class="list-inline-item-time">
                  <%= l spot.created_at, format: :long %>
                </li>

                <!-- アイコン -->
                <ul class="flex justify-end items-center gap-1">
                  <li class="feedback_comment_count list-inline-item-time flex items-center gap-1">
                    <svg class="h-5 w-5 text-gray-500" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">  
                      <path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z" />
                    </svg>
                    <p class="m-0"><%= spot.feedbacks_count %></p>
                  </li>
                  <li class="likes_count list-inline-item-time flex items-center gap-1">
                    <svg class="h-5 w-5 text-red-500" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                      <path stroke="none" d="M0 0h24v24H0z"/>
                      <path d="M12 20l-7 -7a4 4 0 0 1 6.5 -6a.9 .9 0 0 0 1 0a4 4 0 0 1 6.5 6l-7 7"/>
                    </svg>
                    <p class="m-0"><%= spot.likes_count %></p>
                  </li>
                </ul>
              </ul>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/spots/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <h1><%= t('.title') %></h1>
      <%= render 'form', { spot: @spot } %>
    </div>
  </div>
</div>

app/views/spots/index.html.erb
<% content_for :title, "スポット一覧" %>
<div class="pt-5 pb-12 mb-10">  
  <!-- 検索フォーム --!>
  <%= search_form_for @q, class: "search-form md:mt-5 lg:mt-10", url: spots_path, method: :get do |f| %>
    <div class="container pt-12 pb-2">
      <div class="row">
        <div class="col-lg-10 offset-lg-1">
          <div class="flex items-center space-x-2 m-5">
            <%= f.search_field :spot_name_or_address_or_comment_cont, class: "form-control flex-1 border border-gray-300 rounded-lg p-2", placeholder: t('posts.index.search_word') %>
            <%= f.submit t('defaults.search'), class: "bg-purple-500 hover:bg-purple-700 text-white font-bold py-2 px-4 rounded" %>
          </div>
        </div>
      </div>
    </div>
  <% end %>

  <!-- マップ検索ボタン --!>
  <button type="button" class="inline-flex items-center justify-center text-white bg-purple-500 hover:bg-purple-700 focus:ring-4 focus:ring-purple-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 ml-5" id="searchMapButton">
    <svg class="h-5 w-5 text-white-500 mr-1"  width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">  <path stroke="none" d="M0 0h24v24H0z"/>  <circle cx="12" cy="11" r="3" />  <path d="M17.657 16.657L13.414 20.9a1.998 1.998 0 0 1 -2.827 0l-4.244-4.243a8 8 0 1 1 11.314 0z" /></svg>
    <%= t('posts.index.search_map') %>
  </button>

  <!-- リスト表示ボタン --!>
  <button type="button" class="inline-flex items-center justify-center text-white bg-purple-500 hover:bg-purple-700 focus:ring-4 focus:ring-purple-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 ml-5 hidden" id="listDisplayButton">
    <svg class="h-5 w-5 text-white-500 mr-1"  width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">  <path stroke="none" d="M0 0h24v24H0z"/>  <line x1="9" y1="6" x2="20" y2="6" />  <line x1="9" y1="12" x2="20" y2="12" />  <line x1="9" y1="18" x2="20" y2="18" />  <line x1="5" y1="6" x2="5" y2="6.01" />  <line x1="5" y1="12" x2="5" y2="12.01" />  <line x1="5" y1="18" x2="5" y2="18.01" /></svg>
    <%= t('posts.index.list_display') %> 
  </button>

  <!-- タグ検索ボタン --!>
  <button id="toggleSearchFormButton" class="inline-flex items-center justify-center text-white bg-purple-500 hover:bg-purple-700 focus:ring-4 focus:ring-purple-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 ml-5">
    <svg class="h-5 w-5 text-white-500 mr-1"  width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">  <path stroke="none" d="M0 0h24v24H0z"/>  <circle cx="10" cy="10" r="7" />  <line x1="21" y1="21" x2="15" y2="15" /></svg>
    <%= t('posts.index.narrow_down_conditions') %>
  </button>
  
  <!-- タグ検索 --!>
  <div id="searchForm" class="w-full lg:w-8/12 px-4 mx-auto mt-6 hidden">
    <div class="relative flex flex-col min-w-0 break-words w-full mb-6 shadow-lg rounded-lg bg-blueGray-100 border-0 h-full">
      <div class="flex flex-col items-center justify-center h-full bg-green-50 p-2">
        <%= search_form_for @q, url: spots_path, method: :get do |f| %>
          <div class="flex flex-wrap gap-4 mb-4 ml-6">
            <% Tag.all.each do |tag| %>
              <div class="flex items-center">
                <%= f.check_box :tags_id_in, { multiple: true, class: "mr-2" }, tag.id, nil %>
                <%= f.label :tags_id_in, tag.content, value: tag.id, class: "text-sm" %>
              </div>
            <% end %>
          </div>
          <div class="text-center">
            <%= f.submit t('posts.index.narrow_tag'), class: "bg-purple-500 hover:bg-purple-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>


  <!-- Google Map -->
  <div id="googleMap" class="text-center m-5 hidden lg:mb-20">
    <div id="map" class="w-full h-96 sm:h-[600px]" data-spots='<%= @spots.to_json(only: [:id, :latitude, :longitude, :address, :spot_name]) %>'></div>
  </div>


  <!-- 掲示板一覧 --!>
  <div class="row" id="boardList">
    <div class="col-12">
      <div class="row">
        <% if @spots.present? %>
          <%= render partial: 'spots/spot', collection: @spots, as: :spot %>
        <% else %>
          <p><%= t('.no_result') %></p>
        <% end %>
      </div>
    </div>
    <div class="mt-5 mb-20 md:mb-20"><%= paginate @spots %></div>
  </div>
</div>

<%= javascript_pack_tag 'spots_index' %>

app/views/spots/new.html.erb
<% content_for :title, "スポット投稿" %>
<div class="container ">
   <div class="row">
     <div class="col-lg-8 offset-lg-2">
       <%= render 'form', { spot: @spot } %>
     </div>
   </div>
 </div>

app/views/spots/show.html.erb
<% content_for :title, "スポット詳細" %>
<div class="max-w-5xl mx-auto pt-20 ">
  <div class="mb-6">
    <div class="mx-auto px-4 lg:w-4/6">
      
      <!-- 掲示板内容 -->
      <div class="bg-white shadow overflow-hidden sm:rounded-lg mt-5">
        <div class="p-6">
          <div class='flex flex-wrap'>
          <h1 class="text-2xl font-semibold"><%= @spot.spot_name %></h1>
            <div class='w-full md:w-1/3 p-4'>
              <% @spot.spot_images.each do |image| %>
                <%= image_tag image.image.url, class: 'mt-5 w-full h-40 object-cover', size: '150x150' %>
              <% end %>
            </div>
            <div class='w-full md:w-2/3 p-4'>
              <h3 class="text-xl font-semibold inline"><%= @spot.address %></h3>
              <div class="flex flex-wrap items-center">
                <% if @spot.tags.exists? %>
                  <% @spot.tags.each do |tag| %>
                    <span class="bg-purple-500 text-white text-sm font-semibold mr-2 px-4 py-1 rounded-full dark:bg-purple-600 dark:text-white mt-1">
                      <%= tag.content %>
                    </span>
                  <% end %>
                <% end %>
              </div>
              <% if current_user&.own?(@spot) %>
                <%= render 'crud_menus', spot: @spot %>
              <% end %>
              <ul class="flex items-center list-none mt-4">
                <% if @spot.user.avater.present? %> 
                  <%= image_tag @spot.user.avater_url, class:"w-8 border-4 border-white rounded-full" %>
                <% else %>
                  <%= image_tag("default.png", class:"w-8 border-4 border-white rounded-full") %>
                <% end %>
                <li>by <%= @spot.user.first_name %><%= @spot.user.last_name %></li>
              </ul>
              <ul class="list-none mt-4">
                <li><%= l @spot.created_at, format: :long  %></li>
              </ul>
              <h3 class="text-xl font-semibold mt-4"><%= t('activerecord.attributes.spot.comment') %></h3>
              <p class="mt-4"><%= simple_format(@spot.comment) %></p> 
              <% unless current_user&.own?(@spot) %>
                <div id="likes_buttons<%= @spot.id %>">
                  <%= render partial: 'likes/like', locals: { spot: @spot, like: @like} %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <!-- Google Map -->
      <% if @spot.tags.any? { |tag| tag.content == '飲食可' } %>
        <div class="bg-white shadow overflow-hidden sm:rounded-lg mt-5">
          <div class="p-6">
            <div class='flex flex-wrap'>
              <h1 class="text-2xl font-semibold">テイクアウト飲食店</h1>
              <div id="map" data-latitude="<%= @spot.latitude %>" data-longitude="<%= @spot.longitude %>" class="w-full h-96 sm:h-[600px]"></div>
            </div>
          </div>
        </div>
      <% end %>
      <!-- コメントフォーム -->
      <% if logged_in? %>
        <%= render 'feedbacks/form', { spot: @spot, feedback: @feedback} %>
      <% end %>
    </div>
  </div>
</div>
<div class="max-w-5xl mx-auto ">
  <div class="mb-6">
    <div class="mx-auto px-4 lg:w-4/6">
      <!-- コメントエリア -->
      <%= render 'feedbacks/feedback_comments', { feedback: @feedbacks } %>
    </div>
  </div>
</div>

<%= javascript_pack_tag 'spots_show' %>