config/routes.rb
Rails.application.routes.draw do
  root to:'top_page#index'
  get 'home/index'

  resources :users, only: [:new, :create]
  resources :user_sessions, only: [:new, :create, :destroy]
  resource :profile, only: %i[show edit update]
  resources :spots do
    resources :feedbacks, only: %i[create destroy edit update], shallow: true
    resources :likes, only: [:create, :destroy]
  end
  get '/sign_up', to: 'users#new'
  get '/sign_in', to: 'user_sessions#new'
  delete '/sign_out', to: 'user_sessions#destroy', as: :sign_out
  get "guest_login", to: "users#guest_login"
  post "oauth/callback", to: "oauths#callback"
  get "oauth/callback", to: "oauths#callback"
  get "oauth/:provider", to: "oauths#oauth", as: :auth_at_provider
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authentication.rb
class Authentication < ApplicationRecord
    belongs_to :user
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :user
  belongs_to :spot, counter_cache: true
  validates :feedback_comment, presence: true, length: { maximum: 65_535 }
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :spot, counter_cache: true

  validates_uniqueness_of :spot_id, scope: :user_id
end

app/models/spot.rb
class Spot < ApplicationRecord
  belongs_to :user
  has_many :spot_images, dependent: :destroy
  has_many :feedbacks, dependent: :destroy
  has_many :spots_tags, dependent: :destroy
  has_many :tags, through: :spots_tags
  accepts_nested_attributes_for :spot_images, allow_destroy: true
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  geocoded_by :address
  after_validation :geocode

  validates :spot_name, presence: true
  validates :address, presence: true

  def self.ransackable_attributes(auth_object = nil)
    ["address", "comment", "created_at", "id", "latitude", "longitude", "spot_name", "updated_at", "user_id"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["feedbacks", "spot_images", "spots_tags", "tags", "user"]
  end

  def like_user(user_id)
    likes.find_by(user_id: user_id)
  end
end

app/models/spot_image.rb
class SpotImage < ApplicationRecord
    belongs_to :spot
    mount_uploader :image, ImageUploader
end

app/models/spots_tag.rb
class SpotsTag < ApplicationRecord
  belongs_to :spot
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
    enum content: { 屋外: 0, 屋内: 1, 飲食可: 2, 屋根: 3, テーブル: 4, 冷暖房: 5, 自動販売機: 6, トイレ: 7 }

    def self.ransackable_attributes(auth_object = nil)
      ["content", "created_at", "id", "updated_at"]
    end
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  before_create :set_user_id
  

  has_many :spots, dependent: :destroy
  has_many :feedbacks, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_spots, through: :likes, source: :spot
  has_many :authentications, dependent: :destroy
  accepts_nested_attributes_for :authentications
  
  validates :password, length: { minimum: 7 }, if: -> { new_record? || changes[:crypted_password]}
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] },unless: :guest
  validates :last_name, length: { maximum: 255 }, presence: true
  validates :first_name,  length: { maximum: 255 }, presence: true
  validates :email, presence: true
  # self.guest_loginメソッドの場合はユニーク制約を無視する
  validates :email, uniqueness: true ,unless: :guest

  enum gender: { other: 0, male: 1, female: 2 }

  mount_uploader :avater, AvaterUploader

  def own?(object)
    id == object.user_id
  end

  private

    # ランダムなユーザーIDを生成
    def set_user_id
      while self.id.blank? || User.find_by(id: self.id).present? do
        self.id = SecureRandom.base58
      end
    end

    # ゲストユーザーを作成する
    def self.guest_login
      random_pass = SecureRandom.base36
      unique_email = "guest_#{Time.current.to_i}_#{SecureRandom.hex(4)}@example.com"
      create!(
        first_name: "ゲスト",
        last_name: "ユーザー",
        email: unique_email,
        password: random_pass,
        guest: true
      )
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_spot
    
  def create
    @like = @spot.likes.create(user_id: current_user.id)
    respond_to do |format|
      format.js 
    end
  end
    
  def destroy
    @like = @spot.likes.find_by(user_id: current_user.id)
    @like.destroy
    respond_to do |format|
      format.js
    end
  end

  private
    def set_spot
      @spot = Spot.find(params[:spot_id])
    end
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController

  before_action :require_login, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_spot, only: [:edit, :update, :destroy]

  def index
    @q = Spot.ransack(params[:q])
    @spots = @q.result.includes(:user, :tags, :feedbacks, :likes).order(created_at: :desc).page(params[:page]).per(5)

    if @spots.empty?
      flash[:alert] = I18n.t('errors.messages.no_results_found')
      redirect_to spots_path
    end
  end

  def new
    @spot = Spot.new
    @spot.spot_images.build
  end

  def create
    @spot = current_user.spots.new(spot_params)
  
    if params[:spot][:tag_ids].present? && !Tag.where(id: params[:spot][:tag_ids]).count == params[:spot][:tag_ids].count
      flash[:error] = t('posts.create.fall')
      render :new and return
    end
  
    if @spot.save
      redirect_to spots_path, notice: t('posts.create.success')
    else
      flash[:error] = t('posts.create.fall')
      render :new
    end
  end

  def show
    @spot = Spot.find(params[:id])
    @feedback = Feedback.new
    @feedbacks = @spot.feedbacks.includes(:user).order(created_at: :desc)
    @like = @spot.like_user(current_user.id) if current_user
  end

  def edit;end
  
  def update
    if @spot.update(spot_params)
      redirect_to @spot, notice: t('posts.update.success')
    else
      render :edit
    end
  end

  def destroy
    @spot.destroy
    redirect_to spots_path, notice: t('posts.destroy.success')
  end

  private 

  def spot_params
    # `tag_ids`が存在しない場合は、デフォルトで空の配列を設定
    params.require(:spot).permit(:spot_name, :address, :latitude, :longitude, :comment, spot_images_attributes: [:id, :image, :_destroy]).tap do |whitelisted|
      whitelisted[:tag_ids] = params[:spot][:tag_ids] || []
    end
  end

  def require_login
    unless logged_in?
      flash[:error] = t('posts.new.fall')
      redirect_to new_user_session_path # ログインページへのパスを指定
    end
  end

  def set_spot
    @spot = current_user.spots.find_by(id: params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    if logged_in?
      redirect_to root_url
    end
    @user = User.new
  end

  def create
    @user = User.new(user_params) 

    if @user.save
      redirect_to new_user_session_path, notice: t('users.create.success') 
    else
      flash.now[:alert] = t('users.create.fall') 
      render :new
    end
  end

  def guest_login
    if current_user
      redirect_to current_user, alert: t('users.guest_login.fall')
    else
      user = User.guest_login
      log_in user
      redirect_to root_path, notice: t('users.guest_login.success') 
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :bio, :avatar, :gender)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def page_title(page_title = '')
        base_title = 'CHOTTO SPOT'
        
        page_title.empty? ? base_title : page_title + ' | ' + base_title
    end
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/oauths_helper.rb
module OauthsHelper
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/helpers/top_page_helper.rb
module TopPageHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= page_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP&family=Noto+Serif+JP&display=swap" rel="stylesheet">
  </head>

  <body data-turbolinks-cache="false">
    <%= render 'shared/header' %>
    <% flash.each do |key, message| %>
      <div class="flash fixed top-[50px] left-0 w-full text-center z-[1000] bg-purple-500/50 text-white py-2 <%= key %>">
        <%= message %>
      </div>
    <% end %>
    <%= yield %>
    <% if logged_in? %>
      <%= render 'shared/footer' %>
    <% else %>
      <%= render 'shared/before_login_footer' %>
    <% end %>
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDlQkifhqzFwnzn8YJjK9RV7lQiI6aH1d4&libraries=places&callback=initMap"></script>
  </body>
</html>

app/views/shared/_before_login_footer.html.erb
<nav class="w-full p-3 bg-green-300 fixed bottom-0 md:p-5 lg:p-6">
  <div class="flex justify-between max-w-5xl mx-auto items-center">
    <div class="home-buttom text-center md:flex-grow lg:flex-grow-0">
      <%= link_to root_path, class: 'flex flex-col items-center justify-center hover:text-purple-300' do %>
        <svg class="h-5 w-5 mb-2 md:h-7 md:w-7 lg:h-8 lg:w-8" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6"/>
        </svg>
        <span class="text-xs capitalize"><%= t('defaults.home') %></span>
      <% end %>
    </div>
    <div class="search-button text-center md:flex-grow lg:flex-grow-0">
      <%= link_to spots_path, class: 'flex flex-col items-center justify-center hover:text-purple-300' do %>
        <svg class="h-5 w-5 mb-2 md:h-7 md:w-7 lg:h-8 lg:w-8" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">  
          <path stroke="none" d="M0 0h24v24H0z"/>  <circle cx="10" cy="10" r="7" />  <line x1="21" y1="21" x2="15" y2="15" />
        </svg>
        <span class="text-xs capitalize"><%= t('defaults.search') %></span>
      <% end %>
    </div>
    <div class="post-button text-center md:flex-grow lg:flex-grow-0">
      <%= link_to new_spot_path, class: 'flex flex-col items-center justify-center hover:text-purple-300' do %>
        <svg class="h-5 w-5 mb-2 md:h-7 md:w-7 lg:h-8 lg:w-8" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">  
          <path stroke="none" d="M0 0h24v24H0z"/>  <path d="M16 6h3a1 1 0 0 1 1 1v11a2 2 0 0 1 -4 0v-13a1 1 0 0 0 -1 -1h-10a1 1 0 0 0 -1 1v12a3 3 0 0 0 3 3h11" />  <line x1="8" y1="8" x2="12" y2="8" />  <line x1="8" y1="12" x2="12" y2="12" />  <line x1="8" y1="16" x2="12" y2="16" />
        </svg>
        <span class="text-xs capitalize"><%= t('defaults.post') %></span>
      <% end %>
    </div>
  </div>
</nav>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger", id="error_messages">
    <ul class="mb-0">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<nav class="w-full p-3 bg-green-300 fixed bottom-0 md:p-5 lg:p-6">
  <div class="flex justify-between max-w-5xl mx-auto items-center">
    <div class="home-buttom text-center md:flex-grow lg:flex-grow-0">
      <%= link_to root_path, class: 'flex flex-col items-center justify-center hover:text-purple-300' do %>
        <svg class="h-5 w-5 mb-2 md:h-7 md:w-7 lg:h-8 lg:w-8" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6"/>
        </svg>
        <span class="text-xs capitalize"><%= t('defaults.home') %></span>
      <% end %>
    </div>
    <div class="search-button text-center md:flex-grow lg:flex-grow-0">
      <%= link_to spots_path, class: 'flex flex-col items-center justify-center hover:text-purple-300' do %>
        <svg class="h-5 w-5 mb-2 md:h-7 md:w-7 lg:h-8 lg:w-8" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">  
          <path stroke="none" d="M0 0h24v24H0z"/>  <circle cx="10" cy="10" r="7" />  <line x1="21" y1="21" x2="15" y2="15" />
        </svg>
        <span class="text-xs capitalize"><%= t('defaults.search') %></span>
      <% end %>
    </div>
    <div class="post-button text-center md:flex-grow lg:flex-grow-0">
      <%= link_to new_spot_path, class: 'flex flex-col items-center justify-center hover:text-purple-300' do %>
        <svg class="h-5 w-5 mb-2 md:h-7 md:w-7 lg:h-8 lg:w-8" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">  
          <path stroke="none" d="M0 0h24v24H0z"/>  <path d="M16 6h3a1 1 0 0 1 1 1v11a2 2 0 0 1 -4 0v-13a1 1 0 0 0 -1 -1h-10a1 1 0 0 0 -1 1v12a3 3 0 0 0 3 3h11" />  <line x1="8" y1="8" x2="12" y2="8" />  <line x1="8" y1="12" x2="12" y2="12" />  <line x1="8" y1="16" x2="12" y2="16" />
        </svg>
        <span class="text-xs capitalize"><%= t('defaults.post') %></span>
      <% end %>
    </div>
    <div class="my-page-button text-center md:flex-grow lg:flex-grow-0">
      <%= link_to profile_path, class: 'flex flex-col items-center justify-center hover:text-purple-300' do %>
        <svg class="h-5 w-5 mb-2 md:h-7 md:w-7 lg:h-8 lg:w-8" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z"/>
        </svg>
        <span class="text-xs capitalize"><%= t('defaults.mypage') %></span>
      <% end %>
    </div>
  </div>
</nav>

app/views/shared/_header.html.erb
<nav class="bg-green-300 w-full p-2 fixed top-0 z-50">
  <div class="flex justify-between max-w-5xl mx-auto items-center">
    <div class="flex items-center mb-4 md:mb-0 lg:mb-0">
      <%= link_to 'CHOTTO SPOT', root_path, class: 'text-lg md:text-xl lg:text-2xl xl:text-2xl font-bold hover:text-purple-300' %>
    </div>
    <div class="group text-center">
      <% if logged_in? %>
        <%= link_to sign_out_path, method: :delete, class: 'flex flex-col items-center justify-center hover:text-purple-300' do %>
          <svg class="h-4 w-4 md:h-8 lg:h-9 xl:h-10 md:w-8 lg:w-9 xl:w-10 mb-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14"/>
          </svg>
          <span class="text-xs md:text-sm lg:text-base xl:text-lg capitalize"><%= t('defaults.logout') %></span>
        <% end %>
      <% else %>
        <%= link_to new_user_session_path, class: 'flex flex-col items-center justify-center hover:text-purple-300' do %>
          <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 md:h-8 lg:h-9 xl:h-10 md:w-8 lg:w-9 xl:w-10" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 16l-4-4m0 0l4-4m-4 4h14m-5 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h7a3 3 0 013 3v1" />
          </svg>
          <span class="text-xs md:text-sm lg:text-base xl:text-lg capitalize"><%= t('defaults.login') %></span>
        <% end %>
      <% end %>
    </div>
  </div>
</nav>