config/routes.rb
Rails.application.routes.draw do
  root to:'top_page#index'
  get 'home/index'

  resources :users, only: [:new, :create]
  resources :user_sessions, only: [:new, :create, :destroy]
  resource :profile, only: %i[show edit update]
  resources :spots do
    resources :feedbacks, only: %i[create destroy edit update], shallow: true
    resources :likes, only: [:create, :destroy]
  end
  get '/sign_up', to: 'users#new'
  get '/sign_in', to: 'user_sessions#new'
  delete '/sign_out', to: 'user_sessions#destroy', as: :sign_out
  get "guest_login", to: "users#guest_login"
  post "oauth/callback", to: "oauths#callback"
  get "oauth/callback", to: "oauths#callback"
  get "oauth/:provider", to: "oauths#oauth", as: :auth_at_provider
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :user
  belongs_to :spot, counter_cache: true
  validates :feedback_comment, presence: true, length: { maximum: 65_535 }
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController

    def create
      @spot = Spot.find(params[:spot_id]) 
      @feedback = current_user.feedbacks.build(feedback_params)
      respond_to do |format|
        if @feedback.save
          format.js 
        else
          format.js
        end
      end
    end

    def edit
      @feedback = current_user.feedbacks.find(params[:id])
      respond_to do |format|
        format.js
      end
    end


    def update
      @feedback = current_user.feedbacks.find(params[:id])
      respond_to do |format|
        if @feedback.update(feedback_update_params)
          format.js
        else
          format.js { render 'edit' }
        end
      end
    end


    def destroy
      @feedback = current_user.feedbacks.find(params[:id])
      respond_to do |format|
        @feedback.destroy
          format.js
      end
    end
    
    private
  
    def feedback_params
      params.require(:feedback).permit(:feedback_comment).merge(spot_id: params[:spot_id])
    end

    def feedback_update_params
      params.require(:feedback).permit(:feedback_comment)
    end
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/views/feedbacks/_feedback_comment.html.erb
<div id="feedback-<%= feedback.id %>">
  <td>
    <div class="flex items-center space-x-2">
      <% if @spot.user.avater.present? %>
        <%= image_tag @spot.user.avater_url, class: "w-8 h-8 border-4 border-white rounded-full" %>
      <% else %>
        <%= image_tag("default.png", class: "w-8 h-8 border-4 border-white rounded-full") %>
      <% end %>
      <h3 class="text-sm font-semibold"><%= feedback.user.last_name %><%= feedback.user.first_name %></h3>
    </div>
    <div id="js-feedback-<%= feedback.id %>" class = "text-sm">
      <%= t('activerecord.attributes.feedback.feedback_comment') %>
      <%= simple_format(feedback.feedback_comment) %>
    </div>
    <%= form_with model: feedback, local: false do |form| %>
      <div id="js-textarea-feedback-box-<%= feedback.id %>" class="hidden">
        <%= form.text_area :feedback_comment, id: "js-textarea-feedback-#{feedback.id}", class: "form-control mb-1 border border-gray-300 rounded-md shadow-sm p-2 w-full", placeholder: "フィードバックを入力", value: feedback.feedback_comment %>
        <div class="flex items-center space-x-2">
          <%= link_to t('defaults.cancel'), '#', class: 'js-button-edit-feedback_comment-cancel bg-gray-200 hover:bg-gray-300 text-gray-800 font-bold py-2 px-4 rounded-l cursor-pointer', data: { feedback_id: feedback.id } %>
          <%= form.submit t('defaults.update'), class: "js-button-feedback-update bg-purple-500 hover:bg-purple-600 text-white font-bold py-2 px-4 rounded-r cursor-pointer" %>
        </div>
      </div>
    <% end %>
  </td>

  <% if current_user&.own?(feedback) %>
    <div class="text-right">
      <div class="inline-flex justify-center">
        <%= link_to edit_feedback_path(feedback), class: 'js-edit-feedback_comment-button', data: { feedback_id: feedback.id }, remote: true, title: '編集' do %>
          <svg class="h-5 w-5 text-purple-500 hover:text-purple-700" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 20h4l10.5 -10.5a1.5 1.5 0 0 0 -4 -4L4 16v4zM13.5 6.5l4 4" />
          </svg>
        <% end %>
        <%= link_to feedback_path(feedback), method: :delete, class: 'js-delete-feedback_comment-button ml-2', data: { feedback_id: feedback.id, confirm: '本当に削除しますか？' }, title: '削除', remote: true  do %>
          <svg class="h-5 w-5 text-purple-500"  width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">  
            <path stroke="none" d="M0 0h24v24H0z"/>  
            <line x1="4" y1="7" x2="20" y2="7" />  
            <line x1="10" y1="11" x2="10" y2="17" />  
            <line x1="14" y1="11" x2="14" y2="17" />  
            <path d="M5 7l1 12a2 2 0 0 0 2 2h8a2 2 0 0 0 2 -2l1 -12" />  
            <path d="M9 7v-3a1 1 0 0 1 1 -1h4a1 1 0 0 1 1 1v3" />
          </svg>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<script>
document.addEventListener('DOMContentLoaded', () => {
  document.querySelectorAll('.js-button-edit-feedback_comment-cancel').forEach(button => {
    button.addEventListener('click', function(e) {
      e.preventDefault();
      const feedbackId = this.dataset.feedbackId;
      document.querySelector(`#js-textarea-feedback-box-${feedbackId}`).classList.add('hidden');
    });
  });
});
</script>

app/views/feedbacks/_feedback_comments.html.erb
<div class="flex justify-center mt-8 pb-10">
  <div class="w-full max-w-4xl">
    <div class="bg-white shadow-md rounded my-6">
      <div class="p-4" id="js-table-feedback_comment">
        <% @feedbacks.each do |feedback| %>
          <%= render 'feedbacks/feedback_comment', feedback: feedback %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/feedbacks/_form.html.erb
<div class="flex flex-wrap mb-6 max-w-3xl ">
  <div class="w-full lg:w-8/12 mx-auto">
    <%= form_with model: @feedback, url: [@spot, @feedback], id: 'new_feedback_comment',local: false do |f| %>
      <div class="m-4">
        <%= f.label :feedback_comment, class: "block text-gray-700 text-sm font-bold mb-2" %>
        <%= f.text_area :feedback_comment, class: 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline', id: 'js-new-feedback-feedback_comment', rows: 4, placeholder: t('activerecord.attributes.feedback.feedback_comment') %>
      </div>
      <div class="flex items-center justify-center h-32">
        <%= f.submit t('defaults.post'), class: 'bg-purple-500 hover:bg-purple-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline' %>
      </div>
    <% end %>
  </div>
</div>

app/views/feedbacks/create.js.erb
document.querySelector("#error_messages")?.remove();
if (!window.jsTableFeedbackComment) {
  window.jsTableFeedbackComment = document.querySelector("#js-table-feedback_comment");
}

<% if @feedback.errors.present? %>
  if (!window.newFeedbackComment) {
    window.newFeedbackComment = document.querySelector("#new_feedback_comment");
  }
  const errorMessages = `<%= j(render('shared/error_messages', object: @feedback)) %>`;
  window.newFeedbackComment.insertAdjacentHTML('afterbegin', errorMessages);
<% else %>
  // 直接 insertAdjacentHTML にHTMLテンプレートを渡す
  window.jsTableFeedbackComment.insertAdjacentHTML('afterbegin', `<%= j(render('feedbacks/feedback_comment', feedback: @feedback, spot: @spot)) %>`);
  
  // コメント入力フォームの内容をクリア
  document.querySelector("#js-new-feedback-feedback_comment").value = '';
<% end %>

app/views/feedbacks/destroy.js.erb
document.querySelector("div#feedback-<%= @feedback.id %>").remove();

app/views/feedbacks/edit.js.erb
document.querySelectorAll('.js-edit-feedback_comment-button').forEach(button => {
  button.addEventListener('click', function(e) {
    e.preventDefault();
    var textareaBox = document.querySelector("#js-textarea-feedback-box-<%= @feedback.id %>");
    if (textareaBox) {
      textareaBox.classList.remove('hidden');
    }
  });
  var textareaBox = document.querySelector("#js-textarea-feedback-box-<%= @feedback.id %>");
    if (textareaBox) {
        textareaBox.classList.remove('hidden');
    }
});

app/views/feedbacks/update.js.erb
<% if @feedback.errors.any? %>
  // 更新に失敗した場合、エラーメッセージを表示
  document.querySelector('#error_messages').innerHTML = `<%= j(render 'shared/error_messages', object: @feedback) %>`;
<% else %>
  // 更新が成功した場合、コメントの表示を更新
  window.feedbackIdUpdate = '<%= @feedback.id %>'; // `const` の代わりに `window` を使用
  document.querySelector(`#js-feedback-${window.feedbackIdUpdate}`).innerHTML = `<%= j @feedback.feedback_comment %>`;
  
  // テキストエリアを隠す
  document.querySelector(`#js-textarea-feedback-box-${window.feedbackIdUpdate}`).classList.add('hidden');
<% end %>