config/routes.rb
Rails.application.routes.draw do
  root to:'top_page#index'
  get 'home/index'

  resources :users, only: [:new, :create]
  resources :user_sessions, only: [:new, :create, :destroy]
  resource :profile, only: %i[show edit update]
  resources :spots do
    resources :feedbacks, only: %i[create destroy edit update], shallow: true
    resources :likes, only: [:create, :destroy]
  end
  get '/sign_up', to: 'users#new'
  get '/sign_in', to: 'user_sessions#new'
  delete '/sign_out', to: 'user_sessions#destroy', as: :sign_out
  get "guest_login", to: "users#guest_login"
  post "oauth/callback", to: "oauths#callback"
  get "oauth/callback", to: "oauths#callback"
  get "oauth/:provider", to: "oauths#oauth", as: :auth_at_provider
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
  end

  def create
    @user = login(user_params[:email], user_params[:password])

    if @user
      redirect_back_or_to(root_path, notice: t('user_sessions.create.success'))
    else
      flash.now[:alert] = t('user_sessions.create.fall')
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_path, notice: t('user_sessions.destroy.success')
  end

  private

  def user_params
    params.require(:user_session).permit(:email, :password)
  end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/new.html.erb
<% content_for :title, "ログイン" %>
<div class="bg-white sm:bg-gray-200 min-h-screen w-screen flex flex-col justify-center items-center pb-16 pt-10">
  <div class="bg-white shadow-none sm:shadow-lg px-8 sm:px-12 w-full xs:w-full sm:w-8/12 md:w-7/12 lg:w-7/12 xl:w-2/6 h-screen sm:h-auto py-8">
    <div class="text-center w-full font-bold text-3xl text-gray-600 p-4">
      ログイン
    </div>
    <div class="w-full bg-gray-200 my-3" style="height: 1px"></div>
      <%= form_with url: user_sessions_path, scope: :user_session, local: true do |form| %>
        <div class="flex flex-col gap-4 px-0 py-4">
          <div class="relative">
            <%= form.label :email, t('activerecord.attributes.user.email'), class: "text-gray-700" %>
            <%= form.email_field :email, placeholder: t('activerecord.attributes.user.email'), class: "py-2 border border-gray-200 w-full", autocomplete: "email" %>
          </div>
          <div class="relative">
            <%= form.label :password, t('activerecord.attributes.user.password'), class: "text-gray-700" %>
            <%= form.password_field :password, placeholder: t('activerecord.attributes.user.password'), class: "py-2 border border-gray-200 w-full", autocomplete: "current-password" %>
          </div>
          <div class="flex flex-col items-center justify-center gap-2 w-full">
            <%= form.submit t('defaults.login'), class: "border border-indigo-500 hover:bg-indigo-500 hover:text-white duration-100 ease-in-out w-6/12 text-indigo-500 p-3 flex flex-row justify-center items-center gap-1" %>
          </div>
        </div>
      <% end %>
    <div class="my-2 flex flex-row justify-center">
      <span class="absolute bg-white px-4">または</span>
      <div class="w-full bg-gray-200 mt-3" style="height: 1px"></div>
    </div>
    <div class="flex space-x-2 justify-center items-center bg-purple-200 hover:bg-purple-600 text-black py-2 rounded-md transition duration-100 mt-5">
      <%= link_to t('user_sessions.new.guest_login'), guest_login_path %>
    </div>
    <%= link_to auth_at_provider_path(provider: :google), class: "flex space-x-2 justify-center items-center bg-gray-200 hover:bg-gray-600 text-black py-2 rounded-md transition duration-100 mt-5" do %>
      <img class="h-5 cursor-pointer" src="https://i.imgur.com/arC60SB.png" alt="">
      <span><%= t('user_sessions.new.google_login') %></span>
    <% end %>
    <%= link_to t('user_sessions.new.to_register_page'), new_user_path, class: 'text-blue-500 hover:text-blue-800 block text-center mt-4' %>
  </div>
</div>